### ISSUE TITLE
IO lock on ./dockerDev.sh

### ISSUE THREAD

**Issue by polus-arcticus** [desci-labs/nodes#109]
### Description

Attempting to start development environment errors desci-nodes service with this IO lock error 
```
[seed:research object] checking for deployment...
[seed:research object] waiting for ganache...
ganache v7.8.0 (@ganache/cli: 0.9.0, @ganache/core: 0.9.0)
Starting RPC server
OpenError: IO error: lock ../local-data/ganache/LOCK: Resource temporarily unavailable
    at /home/thdev/Documents/desci/nodes/desci-contracts/node_modules/ganache/dist/node/0.js:2:182635
    at /home/thdev/Documents/desci/nodes/desci-contracts/node_modules/ganache/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    at onopen (/home/thdev/Documents/desci/nodes/desci-contracts/node_modules/ganache/dist/node/0.js:2:1344047)
    at /home/thdev/Documents/desci/nodes/desci-contracts/node_modules/ganache/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    at /home/thdev/Documents/desci/nodes/desci-contracts/node_modules/ganache/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
```
docker ps doesn't show the container as running

### Additional Information

![IO-lock](https://github.com/desci-labs/nodes/assets/122753557/c3cb99ac-edc3-4471-a8f9-6e757bec1b11)

on linux mint 21

**Comment by hubsmoke** [comment]
can you please make sure that all docker containers are stopped, then run `make sterile` and then run `dockerDev.sh`

**Comment by hubsmoke** [comment]
this error suggests that two processes are attempting to start ganache (local blockchain) also try doing `ps aux | grep ganache` to see if any processes are running or `lsof -i:8545` to see if any processes are listening on port 8545 which is ganache's default port -- the goal is to turn off that process (`killall ganache-cli`), make sure the lock file is deleted (`make sterile`) and then start the server again (`dockerDev.sh`)

**Comment by hubsmoke** [comment]
hey @polus-arcticus i pushed this fix https://github.com/desci-labs/nodes/commit/4438f386154442a1636667782d32ee8e99e934f0 to hopefully resolve this completely after you told me pkill wasn't doing it

**Comment by hubsmoke** [comment]
going to mark this as solved for now unless you still have issues -- if so please let me know, we'd like to solve this
