### ISSUE TITLE
Make uploads async with a jobID and accurate progress

### ISSUE THREAD

**Issue by hubsmoke** [desci-labs/nodes#132]
Currently nodes-server can timeout with large uploads, additionally the progress is not accurately reflecting a "processing" step

Consider also changing the data model to NOT store the data in IPFS/DAG format in draft mode, and only making it into a DAG for the publish step.

- [ ] Draft mode stores data not in DAG format, improving performance
- [ ] Give each upload a JobID
- [ ] GET progress from JobID, including any processing
- [ ] Update frontend to use JobID format

**Comment by carlaost** [comment]
@hubsmoke can we close this?
