### ISSUE TITLE
Setup Ceramic infrastructure

### ISSUE THREAD

**Issue by remo-desci** [desci-labs/nodes#173]
# Cloud environment
Here are the official docs for running Ceramic in the cloud, including scripts for setting up kubernetes: https://developers.ceramic.network/docs/composedb/guides/composedb-server/running-in-the-cloud

I'm not sure how well those setup scripts work with the rest of our infrastructure.

What needs to be available is the trifecta of an IPFS node, a ceramic node, and a postgres database; each with its own persistent volume. Maybe not currently required, but there are some serious persistence requirements for the ceramic state store, the IPFS store, and the PG database. Since there is likely no-one else pinning the blocks with the codex commits at the moment, the data will be lost unless our node can recover from critical failure.

# Service configuration
Here are the docs on configuring the ceramic service: https://developers.ceramic.network/docs/composedb/guides/composedb-server/server-configurations

**Comment by m0ar** [comment]
@hubsmoke 

## Prep work
1. Create an RDS DB called `ceramic`

## Image
https://hub.docker.com/r/ceramicnetwork/js-ceramic

## Config
Configuration is done by mounting a config file at `/root/.ceramic/daemon.config.json`. Ceramic requires a state store, which is either a PD or an S3 bucket. Up to you what's easiest, I think it should work the same. See config alternative for this below.

```json
{
  "anchor": {
    "ethereum-rpc-url": "[RPC_URL]"
  },
  "http-api": {
    "cors-allowed-origins": [
      ".*"
    ],
    "admin-dids": [
      "did:key:z6MktbKJrMnhVJ37QFTo12911ycm2juKDUzWHDVETu9s5a9T"
    ]
  },
  "ipfs": {
    "mode": "remote",
    "host": "http://[IPFS_IP_ADDRESS]:5001"
  },
  "logger": {
    "log-level": 2,
    "log-to-files": false
  },
  "metrics": {
    "metrics-exporter-enabled": false,
    "metrics-port": 9090
  },
  "network": {
    "name": "testnet-clay"
  },
  "node": {},
  "state-store": {
    "mode": "fs",
    "local-directory": "[PD_MOUNT_PATH]/ceramic/statestore"
  },
  "indexing": {
    "db": "postgres://[DB_USERNAME]:[DB_PASSWORD]@[HOST]/[DB_NAME]",
    "allow-queries-before-historical-sync": true,
    "enable-historical-sync": true,
    "models": []
  }
}
```

### S3 `state-store`
If S3 for the ceramic state store is preferred, change `state-store` to this:
```json
"state-store": {
    "mode": "s3",
    "s3-bucket": "[BUCKET_NAME]"
}
```

If so, these are the required permissions on the bucket:
```json
"Action": [
  "s3:ListBucket",
  "s3:GetObject",
  "s3:PutObject",
  "s3:DeleteObject"
]
```

## Running container
This is the command to run the container, I'm not sure how these convert to kube config:
```bash
docker run -d \
  -p 7007:7007 \
  -v /path_on_volume_for_daemon_config:/root/.ceramic/daemon.config.json \
  -v /path_on_volume_for_ceramic_statestore:/root/.ceramic/statestore \
  -e NODE_ENV=production \
  --name js-ceramic \
  ceramicnetwork/js-ceramic:latest
```

### S3 alternative
If using S3 for the datastore, this is the corresponding command:
```bash
docker run -d \
  -p 7007:7007 \
  -v /path_for_daemon_config:/root/.ceramic/daemon.config.json \
  -e NODE_ENV=production \
  -e AWS_ACCESS_KEY_ID=s3_access_key_id \
  -e AWS_SECRET_ACCESS_KEY=s3_secret_access_key \
  --name js-ceramic \
  ceramicnetwork/js-ceramic:latest
```

## Additional info
There is a YAML file here for health checks etc, if you want to set that up: https://github.com/ceramicstudio/simpledeploy/blob/aba2957f6add0a13d218bd04b352280dc6f70861/k8s/base/composedb/manifests/composedb.yaml
