### ISSUE TITLE
Version Switcher after Publish

### ISSUE THREAD

**Issue by hubsmoke** [desci-labs/nodes#472]

**Comment by hubsmoke** [comment]
Frontend problem where Node Switcher displays invalid versions after publish

**Comment by Electromorphous** [comment]
The versions from `useNodeCollection()` are correct, hence showing up correctly on the profile page, but the bug is in `useNodeHistory()` hook which returns the wrong versions and renders in the history tab and `DriveVersionSwitcher.tsx`

**Comment by m0ar** [comment]
Closed by @hubsmoke with https://github.com/desci-labs/nodes-web-v2/pull/876
