### ISSUE TITLE
Search attestations

### ISSUE THREAD

**Issue by Electromorphous** [desci-labs/nodes#662]

**Comment by Queen-esther01** [comment]
Hi @kadamidev I reassigned to you because there is no API for searching attestations, the UI already exists.

**Comment by jring-o** [comment]
Reassigning to @shadrach-tayo because you are more familiar with this API

**Comment by jring-o** [comment]
Should be done by Monday

**Comment by Queen-esther01** [comment]
Reassigned to myself because I had some time to work on it.
