### ISSUE TITLE
Implementation of manuscript preview, emailing manuscript to owner and contributors, and success screen after publishing

### ISSUE THREAD

**Issue by Electromorphous** [desci-labs/nodes#667]
### Designs
https://www.figma.com/design/cA1P4T5TLhWdYx2KaoZ1RF/DeSci-Nodes-V3?node-id=8100-7876&t=eQC1K6nPond9PtI8-4

We will not send email invites in step 3 when authors are added, instead we will send an email to all contributors after the node has been published and the manuscript has been generated, with 3 buttons:
1. for viewing the manuscript that was generated from the flow
2. for viewing the research object
3. for verifying their contribution to the research object

It is supposed to be similar to the email we are sending right now but with an additional button for downloading/viewing the manuscript. And the copies of our emails need to be updated, as they still say "node" instead of research object.

- [x] Designs
- [ ] Code

**Comment by jring-o** [comment]
Submission package flow is pending -- fixing bugs regarding CID
