### ISSUE TITLE
Make Drive API include a list of components within the folder

### ISSUE THREAD

**Issue by hubsmoke** [desci-labs/nodes#98]
Andre requested an enhancement to Drive API for capybara, given a folder we want to know the types of components within them, possibly with a count. Also data size and perhaps size by type

**Comment by andrepology** [comment]
The reason for this request is that when a user opens the metadata preview for a folder, the most important metadata to give them an overview about the folder is what it contains, which can be described through count of files, breakdown of files by type (eg 25 code, 30 data ), and folder size (which we have), in that order of importance. 
 
Note that these three are my best guesses, if you have ideas for similar properties that serve the same purpose, please suggest and add them!

**Comment by hubsmoke** [comment]
@kadamidev IMO this is an expensive operation because it requires us to recalculate the numbers everytime the manifest changes

**Comment by hubsmoke** [comment]
we should consider a solution that does not involve recursing through all the files each time a manifest updates. i suppose we can run this operation on top of the cached redis full tree and not cache the result and see if performance works ok
